Add `--recreateStationIdOnError`
filecoin-station/core pull request #563
Opened 2024-08-01 11:10 UTC by juliangruber

For https://github.com/filecoin-station/desktop/issues/1726

I decided to add this flag instead of a new exit code (as suggested in https://github.com/filecoin-station/desktop/issues/1726#issuecomment-2262594686), because with the new exit code Station Desktop needs to know where Station Core stores its internal files, and this coupling isn't necessary.

2024-08-01 11:13 UTC, juliangruber commented
Blocks https://github.com/filecoin-station/desktop/pull/1742

2024-08-01 13:46 UTC, bajtos requested changes
The proposed implementation LGTM.

Let's add some test please.

- https://github.com/filecoin-station/core/blob/main/test/cli.js
- https://github.com/filecoin-station/core/blob/main/test/station-id.test.js

2024-08-02 08:28 UTC, bajtos approved these changes
👌🏻 

What do you think about improving the following error message to explain to the user that they can re-run Station Core with the new flag to fix the problem?

https://github.com/filecoin-station/core/blob/fe02c6e4e10f043743a640c6fc807c4af8f76c8f/lib/station-id.js#L64

2024-08-02 09:25 UTC, juliangruber commented
Great idea!

2024-08-02 09:26 UTC, merged